name: 'Organizational GitHub Security Scan (CodeQL)'

on:
  workflow_call:
    inputs:
      language:
        description: 'The language of the code to analyze (e.g., csharp, javascript, python, go, java, cpp).'
        required: true
        type: string
      # For C#, Go, Java, JavaScript/TypeScript, Python, Ruby, CodeQL can often autobuild.
      # For other languages or complex builds, manual build steps might be needed.
      # This template will primarily rely on autobuild or a simple build command.
      run-autobuild:
        description: 'Set to true to attempt CodeQL autobuild (recommended for supported languages like C#).'
        required: false
        type: boolean
        default: true
      custom-build-command:
        description: 'If not using autobuild, provide the command to build the code for CodeQL analysis.'
        required: false
        type: string
        default: ''
      codeql-config-file:
        description: 'Optional path to a custom CodeQL configuration file.'
        required: false
        type: string
        default: '' # Default is no custom config file
      checkout-path: # If code is not in the root
        description: 'Path to the checked-out code directory relative to GITHUB_WORKSPACE.'
        required: false
        type: string
        default: '.'
      # Add input for specifying CodeQL version if needed, for now uses default from action
    outputs:
      sarif-file:
        description: 'Path to the SARIF results file generated by CodeQL.'
        value: ${{ jobs.codeql-scan.outputs.sarif-file }}

jobs:
  codeql-scan:
    runs-on: ubuntu-latest
    outputs:
      sarif-file: ${{ steps.analyze.outputs.sarif-id }} # The action outputs sarif-id which is the path

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Recommended for CodeQL for better analysis history
          path: ${{ inputs.checkout-path }} # Checkout to specified path

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ inputs.language }}
          config-file: ${{ inputs.codeql-config-file != '' && format('{0}/{1}', inputs.checkout-path, inputs.codeql-config-file) || '' }}
          # queries: '+security-extended' # Example: run more queries, can be an input
          # source-root: ${{ inputs.checkout-path }} # Specify source root if not default

      # Autobuild attempts to build the code.
      # If autobuild is not suitable, a manual build step is required here.
      - name: Autobuild
        if: inputs.run-autobuild == true && inputs.custom-build-command == ''
        uses: github/codeql-action/autobuild@v3
        working-directory: ${{ inputs.checkout-path }}

      # If a custom build command is provided, run it.
      # This step should be customized by the calling workflow if autobuild is insufficient.
      - name: Custom Build (if specified)
        if: inputs.custom-build-command != ''
        run: |
          echo "Running custom build command: ${{ inputs.custom-build-command }}"
          ${{ inputs.custom-build-command }}
        shell: bash # Or powershell, etc., could be an input
        working-directory: ${{ inputs.checkout-path }}

      - name: Perform CodeQL Analysis
        id: analyze
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{inputs.language}}" # For uploading SARIF results with a category

      # Note on Secret Scanning & Dependency Review:
      # GitHub's native Secret Scanning is primarily a repository-level setting that scans continuously.
      # Dependency Review (and Dependabot alerts) are also GitHub features.
      # This workflow focuses on CodeQL SAST.
      # Consider adding a separate action for PR-based secret checks if desired,
      # or document best practices for enabling GitHub's native features.